/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.schedulo.app.panels;

import com.eclipsesource.json.JsonObject;
import com.schedulo.app.objects.CourseObject;
import com.schedulo.app.objects.ScoredObject;
import com.schedulo.app.util.InstanceData;
import com.schedulo.app.util.OneJsonUtil;
import com.schedulo.app.util.ScheduleEvaluationUtil;
import com.schedulo.app.util.WindowUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;

/**
 *
 * @author jmaher
 */
public class TextClassSearch extends javax.swing.JPanel {

    /**
     * Creates new form TextClassSearch
     */
    public TextClassSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 246));
        setPreferredSize(new java.awt.Dimension(680, 493));
        setSize(new java.awt.Dimension(680, 493));

        jPanel1.setBackground(new java.awt.Color(198, 40, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Advanced Class Search (Text Input)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jList1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Add");
        jButton1.setToolTipText("Add a class to your course search");
        jButton1.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton1.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton1.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.setToolTipText("Clear this search");
        jButton2.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton2.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton2.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Remove");
        jButton3.setToolTipText("Remove the selected course from your search");
        jButton3.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton3.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton3.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Edit");
        jButton4.setToolTipText("Edit the selected course's search parameters");
        jButton4.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton4.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton4.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("To create a schedule, add individual classes by specifying search parameters. When you are done, press");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("the search arrow to the right of the list. To go back, press the back arrow to the left of the list. You can");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("add however many courses you would like, but being too specific makes it harder to make your schedule.");

        jButton5.setText("Search");
        jButton5.setToolTipText("Add a class to your course search");
        jButton5.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton5.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton5.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("DEF");
        jButton6.setToolTipText("Add a class to your course search");
        jButton6.setMaximumSize(new java.awt.Dimension(124, 29));
        jButton6.setMinimumSize(new java.awt.Dimension(124, 29));
        jButton6.setPreferredSize(new java.awt.Dimension(124, 29));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO figure out how to clear jlist1.
        jList1.setListData(new String[0]);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        InstanceData.store("list_to_update", jList1);
        WindowUtil.OpenTemporaryFrame("add_class", new ClassAddDialogue());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String oldVal = jList1.getSelectedValue();
        if(oldVal == null){
            //Nothing is selected
            return;
        }
        InstanceData.store("list_to_update", jList1);
        WindowUtil.OpenTemporaryFrame("add_class", new ClassAddDialogue(oldVal));
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String selectedKey = jList1.getSelectedValue();
        if(selectedKey == null){
            //Nothing is selected
            return;
        }
        AbstractListModel alm = (AbstractListModel<String>) jList1.getModel();
        List<String> toAdd = new ArrayList<String>();
        for(int i = 0; i < alm.getSize(); i++){
            String thisVal = (String) alm.getElementAt(i);
            if(!thisVal.equals(selectedKey)){
                toAdd.add(thisVal);
            }
        }
        String[] newArr = new String[toAdd.size()];
        for(int i = 0; i < newArr.length; i++){
            newArr[i] = toAdd.get(i);
        }
        jList1.setListData(newArr);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        AbstractListModel alm = (AbstractListModel<String>) jList1.getModel();
        List<CourseObject> toSearch = new ArrayList<CourseObject>();
        
        if(InstanceData.contains("DEMO")){
            toSearch = (List<CourseObject>) InstanceData.fetch("DEMO");
        }
        
        for(int i = 0; i < alm.getSize(); i++){
            String thisVal = (String) alm.getElementAt(i);
            toSearch.add((CourseObject) InstanceData.fetch(thisVal));
        }
        
        OneJsonUtil oju = new OneJsonUtil();
        oju.loadJson("/var/folders/q9/hmwp7w1s1fg2mv80gg7jlvbw0000gn/T/json_data.json");
        List<List<JsonObject>> results = oju.generateValidSchedules("201720", toSearch);
        
        // Do any pre-evaluation for the different metrics
        ScheduleEvaluationUtil.preClumpedness(results);
        
        // Do evaluation for the different metrics
        List<ScoredObject> scores = new ArrayList<ScoredObject>();
        
        int index = 1;
        for(List<JsonObject> item : results){
            ScoredObject so = new ScoredObject(item,index);
            so.putScore("clumpedness", ScheduleEvaluationUtil.clumpedness(item));
            scores.add(so);
            index+=1;
        }
        
        scores.sort(null);
        
        WindowUtil.CloseCurrentFrame();
        WindowUtil.OpenUndecoratedFrame(new SearchResultsDisplay(scores));
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        List<CourseObject> toFind = new ArrayList<CourseObject>();
        CourseObject co = new CourseObject();
        co.setSubject("ENGR");
        co.setCourseNumber("2002");
        toFind.add(co);
        
        CourseObject co1 = new CourseObject();
        co1.setTitle("Principles of Programming Languages");
        toFind.add(co1);
        
        CourseObject co2 = new CourseObject();
        co2.setTitle("Human Computer Interaction");
        toFind.add(co2);
        
        CourseObject co3 = new CourseObject();
        co3.setTitle("General Physics for Engineering and Science Majors");
        toFind.add(co3);
        
        CourseObject co4 = new CourseObject();
        co4.setTitle("Disc-PHYS 2514-030");
        toFind.add(co4);//Engineering Orientation Experience for Transfer Students
        
        CourseObject co5 = new CourseObject();
        co5.setTitle("Engineering Orientation Experience for Transfer Students");
        toFind.add(co5);
        
        InstanceData.store("DEMO", toFind);
    }//GEN-LAST:event_jButton6MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
